project:
  type: website
  output-dir: docs

website:
  title: "yonatan-grossman.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: gallery.qmd
        text: Gallery
      - href: projects.qmd
        text: Projects
      - resume.qmd

format:
  html:
    echo: false
    message: false
    warning: false
    results: 'hide'
    theme:
      light: journal
      dark: solar
    css: styles.css
    toc: true

editor: visual

