project:
  type: website
  output-dir: docs

website:
  title: "yonatan-grossman.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: gallery.qmd
        text: Gallery
      - href: projects.qmd
        text: Projects
      - href: resume_Grossman_Yonatan.pdf
        text: Resume

format:
  html:
    echo: false
    message: false
    warning: false
    results: 'hide'
    theme:
      light: journal
      dark: solar
    css: styles.css
    toc: true

editor: visual

