---
title: "Things I love to do outside of school"
toc: true
---

#### Staying active

I've never really enjoyed going to the gym, but I do love to stay active. Over my 3 years at UCSB I have spent a lot of my time surfing, hiking, swimming, rock climbing, juggling, dancing, and, most recently, started learning parkour and jiu jitsu. I always enjoy learning a new physical skill and it's been really cool learning how to move in new and different ways.

This also includes spending as much time in nature as possible, and outside of spending time by the ocean and in the mountains I have managed to visit five of the nine national parks in California with plans to visit at least two more before I graduate.

#### Working creatively

Although this past quarter I have been somewhat focused on my work since I've been swamped with classes, I've been lucky enough to spend a good chunk of my time on creative outlets. I've acted for and assistant directed for film, as well as acted and written for several theater productions. I've also collaborated with friends on scripts and always have a few writing projects in my back pockets. Since taking GIS classes earlier this year I have taken an interest in map-making, and been using map-making as a creative outlet for my passion for cartography and data science.

#### Cooking

Although I always thought I was a somewhat decent cook, living on my own and shopping for myself has really pushed me to learn more ways of feeding myself. No one tells you that one of the hardest part of growing up is having to decide what to eat 2-3 times a day for the rest of your life, but it really is. I've taken this opportunity, however, to improve my skill in the kitchen and branch out into new territories. Two years ago I had never really cooked meat of any kind by myself, and now I have several recipes in the back of my mind for most type of protein. It's also given me an education in creativity, because sometime it's 10pm, you need to make dinner, and all you have is three cans of beans and tomatoes and some spices. I've really enjoyed increasing my competency in the kitchen and now look forward to trying out new recipes whenever I can.
