---
title: "ArcGIS"
format: html
---

## In class

I started learning what GIS was how to use the software earlier this year, and have since taken two of the classes offered at UCSB with the intention to take two more next year. I've really enjoyed getting to toy with spatial data and have even used the skills I developed to work on my own projects. 

For my final project in one of my classes I was placed in a group with 3 other people and we were supposed to come up with our own project and then collect data and try to figure it out. My group decided to try to address the feasibility of re-introducing grizzly bears to California.

We collected data from various online sources, uploaded them to arcGIS online, and then worked together to create this storymap.


<iframe src="https://storymaps.arcgis.com/stories/5faf705556174a63a4c84a16f78f1bb6"
        width="100%" height="800" frameborder="0" allowfullscreen>
</iframe>



## Outside class

I've really enjoyed learning about and using GIS software, and have used it in some of my own projects as well. I am currently working on a project on my own that compares the distribution of various religions in central and south Asia, specifically the Indian subcontinent.